#!/bin/bash
xfce4-terminal --role bot1 & # -e "node ~/BotFolder/Automatic/automatic.js" &
xfce4-terminal --role bot2 & # -e "node ~/BotFolder/'Schubi Automatic'/automatic.js " &
xfce4-terminal --role bot3 & # -e "node ~/BotFolder/'Schubi Bot'/bot.js" &
xfce4-terminal --role bot4 & # -e "node ~/BotFolder/'current bot'/bot.js" &
chromium &
