#! /bin/sh

sxhkd &

bspc monitor -d terminals browser normal

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a xfce4-terminal desktop='^1'

 # change the desktop number here
FLOATING_DESKTOP_ID=$(bspc query -D -d '^3')

bspc subscribe node_manage | while read -a msg ; do
   desk_id=${msg[2]}
   wid=${msg[3]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done &

while true; do
	CURRENT_DESKTOP_NAME=$(bspc query -D -d --names)
	COLORS=("#000000" "#000000" "#000000")
	NAMES=("terminals" "browser" "normal")
	for index in {0..2}; do
		if [ "$CURRENT_DESKTOP_NAME" == "${NAMES[$index]}" ]; do


